services:
  idhan-postgres:
    image: postgres:18
    container_name: idhan-postgres
    environment:
      POSTGRES_USER: idhan
      POSTGRES_PASSWORD: idhan
      POSTGRES_DB: idhan-db
    volumes:
      - idhan_pg18:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U idhan -d idhan-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  idhan-server:
    build:
      context: .
    container_name: idhan-server
    environment:
      IDHAN_DATABASE_HOST: idhan-postgres
      IDHAN_DATABASE_USER: idhan
      IDHAN_DATABASE_PASSWORD: idhan
      IDHAN_DATABASE_DATABASE: idhan-db
    ports:
      - "16609:16609"
    security_opt:
      - seccomp=unconfined
    depends_on:
      idhan-postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  idhan_pg18:
